default: &default
  sistema_nome:             <%= ENV["SISTEMA_NOME"] %>
  sistema_apelido:          <%= ENV["SISTEMA_APELIDO"] %>
  admin_name:               <%= ENV["ADMIN_NAME"] %>
  admin_email:              <%= ENV["ADMIN_EMAIL"] %>
  admin_username:           <%= ENV["ADMIN_EMAIL"].split('@')[0] %>
  admin_password:           <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username:  <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password:  <%= ENV["GMAIL_PASSWORD"] %>
  email_nome:               "debora.junges@ifc.edu.br"
  # email_nupe:               "nupe@fraiburgo.ifc.edu.br"

development:
  <<: *default
  secret_key_base:          <%= ENV["DEV_SECRET_KEY_BASE"] %>
  sistema_versao:           <%= ENV["DEV_SISTEMA_VERSAO"] %>
  domain_name:              <%= ENV["DEV_DOMAIN_NAME"] %>
  default_url_options:      <%= ENV["DEV_DEFAULT_URL_OPTIONS"] %>

test:
  <<: *default
  secret_key_base:          <%= ENV["TST_SECRET_KEY_BASE"] %>
  sistema_versao:           <%= ENV["TST_SISTEMA_VERSAO"] %>
  domain_name:              <%= ENV["TST_DOMAIN_NAME"] %>
  default_url_options:      <%= ENV["TST_DEFAULT_URL_OPTIONS"] %>

staging:
  <<: *default
  secret_key_base:          <%= ENV["STG_SECRET_KEY_BASE"] %>
  sistema_versao:           <%= ENV["STG_SISTEMA_VERSAO"] %>
  domain_name:              <%= ENV["STG_DOMAIN_NAME"] %>
  default_url_options:      <%= ENV["STG_DEFAULT_URL_OPTIONS"] %>

production:
  <<: *default
  secret_key_base:          <%= ENV["PRD_SECRET_KEY_BASE"] %>
  sistema_versao:           <%= ENV["PRD_SISTEMA_VERSAO"] %>
  domain_name:              <%= ENV["PRD_DOMAIN_NAME"] %>
  default_url_options:      <%= ENV["PRD_DEFAULT_URL_OPTIONS"] %>
